#!/bin/bash

git diff --diff-filter=d --name-only main | grep -E '(\.h|\.hpp|\.cpp|\.cu|\.c|\.inl)$' | xargs clang-format -style=file -i

#find src tests \( -name 'CMakeLists.txt' \)  | xargs cmake-format -i
