services:
  hub:
    image: minidb_1.0
    container_name: hub
    networks: 
      - default
    environment:
        CONN_CONF: "node1 8081" 
    command: "tail -f /dev/null"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node1:
    image: minidb_1.0
    container_name: node1
    networks: 
      - default
    environment:
        NODE1_IP: "8081"
    command: "./setup_scripts/init_node1.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

