services:
  hub:
    image: minidb_1.0
    container_name: hub
    networks: 
      - default
    environment:
      RPC_CONNECTIONS: "node1:8081 node2:8082 node3:8083 node4:8084"
      TCP_CONNECTIONS: "8108 8109 8110 8111"
    command: "tail -f /dev/null"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node1:
    image: minidb_1.0
    container_name: node1
    networks: 
      - default
    environment:
        NODE1_IP: "8081"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node1.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node2:
    image: minidb_1.0
    container_name: node2
    networks: 
      - default
    environment:
        NODE2_IP: "8082"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node2.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node3:
    image: minidb_1.0
    container_name: node3
    networks: 
      - default
    environment:
        NODE3_IP: "8083"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node3.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node4:
    image: minidb_1.0
    container_name: node4
    networks: 
      - default
    environment:
        NODE4_IP: "8084"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node4.sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  

