services:
  hub:
    image: minidb_1.0
    container_name: hub
    networks: 
      - default
    environment:
      RPC_CONNECTIONS: "node1:8081 node2:8082 192.168.1.17:8083 192.168.1.17:8084"
      TCP_CONNECTIONS: "8108 8109 8110 8111"
    command: "tail -f /dev/null"

  node1:
    image: minidb_1.0
    container_name: node1
    networks: 
      - default
    environment:
        NODE1_IP: "8081"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node1.sh"

  node2:
    image: minidb_1.0
    container_name: node2
    networks: 
      - default
    environment:
        NODE2_IP: "8082"
        HUB_ADDRESS: "hub"
    command: "./setup_scripts/init_node2.sh"

  

