version: '3.9'

services:
  node3:
    image: minidb_1.0
    container_name: node3
    networks: 
      - default
    environment:
        RPC_PORT: "8083"
        TCP_PORT: "8110"
        HUB_ADDRESS: "192.168.1.40"
    ports:
      - 8083:8083
    command: "node"

  node4:
    image: minidb_1.0
    container_name: node4
    networks: 
      - default
    environment:
        RPC_PORT: "8084"
        TCP_PORT: "8111"
        HUB_ADDRESS: "192.168.1.40"
    ports:
      - 8084:8084
    command: "node"

  

