// Refactor this approach
#include "AbstractFactory.h"
#include "EmptyType.h"
#include "HierarchyGenerators.h"
#include "NullType.h"
#include "Sequence.h"
#include "Typelist.h"
#include "TypelistMacros.h"
#include "TypeManip.h"
#include "TypeTraits.h"